# Generated by Django 5.0.4 on 2024-04-17 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.CharField(max_length=255)),
                ('headline', models.TextField()),
                ('trail_text', models.TextField()),
                ('body', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('summary', models.TextField()),
                ('question', models.TextField()),
                ('answers', models.CharField(choices=[('U', 'Undecided'), ('Y', 'Yes'), ('N', 'No')], default='U', max_length=1)),
            ],
        ),
    ]
