# Generated by Django 5.0.4 on 2024-04-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='answers',
        ),
    ]
