# Generated by Django 5.0.4 on 2024-04-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_article_question_alter_article_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='article',
            name='web_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
