# Generated by Django 5.0.4 on 2024-04-19 05:30

import datetime
import django.core.validators
import django.db.models.deletion
import polls.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_article_options_alter_article_web_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2024, 4, 19)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField(blank=True, null=True, validators=[polls.models.validate_current_or_past_year])),
                ('postcode', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Postcode must be a four-digit number.', regex='^\\d{4}$'), polls.models.validate_postcode_range])),
                ('gender', models.CharField(blank=True, choices=[('W', 'Would rather not say'), ('F', 'Female or woman'), ('M', 'Male or man'), ('X', 'Non-binary'), ('O', 'Other')], max_length=1, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=16)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
